services:
  frontend:
    container_name: frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - app-network
    ports:
      - "80:80"

  backend:
    container_name: backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - app-network

networks:
  app-network:
    driver: bridge