services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    networks:
      - app-network

  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend/nginx/dev/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge