services:
  mongo:
    image: mongo:4.2-bionic
    hostname: todo_mongodb
    container_name: mongo
    environment:
      - MONGO_INITDB_DATABASE=todo_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - ./backend/mongo/init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
      # - mongodbdata:/data/db
    networks:
      - app-network

  backend:
    container_name: backend
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
    networks:
      - app-network
    depends_on:
      - mongo

  frontend:
    container_name: frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend/src:/app/src
    networks:
      - app-network
    depends_on:
      - backend


  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend/nginx/dev/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - backend
      - frontend

networks:
  app-network:
    driver: bridge

# volumes:
#     mongodbdata: